# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'robot_arm_gui.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QComboBox, QFrame,
    QGroupBox, QHBoxLayout, QLabel, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QSlider, QSpinBox, QStatusBar, QTabWidget,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(801, 600)
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.aboutAction = QAction(MainWindow)
        self.aboutAction.setObjectName(u"aboutAction")
        self.aboutAction.setMenuRole(QAction.AboutRole)
        self.exitAction = QAction(MainWindow)
        self.exitAction.setObjectName(u"exitAction")
        self.exitAction.setMenuRole(QAction.QuitRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 801, 551))
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setTabBarAutoHide(False)
        self.setupTab = QWidget()
        self.setupTab.setObjectName(u"setupTab")
        self.frame = QFrame(self.setupTab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 10, 781, 81))
        self.frame.setFrameShape(QFrame.Box)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setLineWidth(1)
        self.refreshButton = QPushButton(self.frame)
        self.refreshButton.setObjectName(u"refreshButton")
        self.refreshButton.setGeometry(QRect(100, 19, 91, 45))
        self.comboBox = QComboBox(self.frame)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(197, 20, 151, 43))
        self.comboBox.setMaxCount(10)
        self.connectionLabel = QLabel(self.frame)
        self.connectionLabel.setObjectName(u"connectionLabel")
        self.connectionLabel.setEnabled(True)
        self.connectionLabel.setGeometry(QRect(21, 20, 151, 41))
        self.connectButton = QPushButton(self.frame)
        self.connectButton.setObjectName(u"connectButton")
        self.connectButton.setGeometry(QRect(351, 19, 81, 45))
        self.connectButton.setCheckable(False)
        self.statusLabel = QLabel(self.frame)
        self.statusLabel.setObjectName(u"statusLabel")
        self.statusLabel.setEnabled(True)
        self.statusLabel.setGeometry(QRect(440, 20, 201, 41))
        self.comboBox.raise_()
        self.connectionLabel.raise_()
        self.connectButton.raise_()
        self.statusLabel.raise_()
        self.refreshButton.raise_()
        self.infoFrame = QFrame(self.setupTab)
        self.infoFrame.setObjectName(u"infoFrame")
        self.infoFrame.setGeometry(QRect(10, 110, 781, 321))
        self.infoFrame.setFrameShape(QFrame.Box)
        self.infoFrame.setFrameShadow(QFrame.Raised)
        self.label_3 = QLabel(self.infoFrame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 20, 741, 291))
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.tabWidget.addTab(self.setupTab, "")
        self.sliderTab = QWidget()
        self.sliderTab.setObjectName(u"sliderTab")
        self.frame_2 = QFrame(self.sliderTab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 10, 781, 311))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QFrame.WinPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayoutWidget = QWidget(self.frame_2)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 10, 759, 292))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.axisLabelVertical = QVBoxLayout()
        self.axisLabelVertical.setObjectName(u"axisLabelVertical")
        self.axisLabel = QLabel(self.horizontalLayoutWidget)
        self.axisLabel.setObjectName(u"axisLabel")

        self.axisLabelVertical.addWidget(self.axisLabel)

        self.axisLabel_2 = QLabel(self.horizontalLayoutWidget)
        self.axisLabel_2.setObjectName(u"axisLabel_2")

        self.axisLabelVertical.addWidget(self.axisLabel_2)

        self.axisLabel_3 = QLabel(self.horizontalLayoutWidget)
        self.axisLabel_3.setObjectName(u"axisLabel_3")

        self.axisLabelVertical.addWidget(self.axisLabel_3)

        self.axisLabel_4 = QLabel(self.horizontalLayoutWidget)
        self.axisLabel_4.setObjectName(u"axisLabel_4")

        self.axisLabelVertical.addWidget(self.axisLabel_4)

        self.axisLabel_5 = QLabel(self.horizontalLayoutWidget)
        self.axisLabel_5.setObjectName(u"axisLabel_5")

        self.axisLabelVertical.addWidget(self.axisLabel_5)

        self.axisLabel_6 = QLabel(self.horizontalLayoutWidget)
        self.axisLabel_6.setObjectName(u"axisLabel_6")

        self.axisLabelVertical.addWidget(self.axisLabel_6)


        self.horizontalLayout.addLayout(self.axisLabelVertical)

        self.axisSpinBoxVertical = QVBoxLayout()
        self.axisSpinBoxVertical.setObjectName(u"axisSpinBoxVertical")
        self.axisSpinBox = QSpinBox(self.horizontalLayoutWidget)
        self.axisSpinBox.setObjectName(u"axisSpinBox")
        self.axisSpinBox.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.axisSpinBox.setCorrectionMode(QAbstractSpinBox.CorrectToNearestValue)
        self.axisSpinBox.setKeyboardTracking(False)
        self.axisSpinBox.setMaximum(360)
        self.axisSpinBox.setValue(180)

        self.axisSpinBoxVertical.addWidget(self.axisSpinBox)

        self.axisSpinBox_2 = QSpinBox(self.horizontalLayoutWidget)
        self.axisSpinBox_2.setObjectName(u"axisSpinBox_2")
        self.axisSpinBox_2.setKeyboardTracking(False)
        self.axisSpinBox_2.setMaximum(180)
        self.axisSpinBox_2.setValue(130)

        self.axisSpinBoxVertical.addWidget(self.axisSpinBox_2)

        self.axisSpinBox_3 = QSpinBox(self.horizontalLayoutWidget)
        self.axisSpinBox_3.setObjectName(u"axisSpinBox_3")
        self.axisSpinBox_3.setKeyboardTracking(False)
        self.axisSpinBox_3.setMaximum(180)
        self.axisSpinBox_3.setValue(180)

        self.axisSpinBoxVertical.addWidget(self.axisSpinBox_3)

        self.axisSpinBox_4 = QSpinBox(self.horizontalLayoutWidget)
        self.axisSpinBox_4.setObjectName(u"axisSpinBox_4")
        self.axisSpinBox_4.setKeyboardTracking(False)
        self.axisSpinBox_4.setMaximum(180)
        self.axisSpinBox_4.setValue(60)

        self.axisSpinBoxVertical.addWidget(self.axisSpinBox_4)

        self.axisSpinBox_5 = QSpinBox(self.horizontalLayoutWidget)
        self.axisSpinBox_5.setObjectName(u"axisSpinBox_5")
        self.axisSpinBox_5.setKeyboardTracking(False)
        self.axisSpinBox_5.setMaximum(180)
        self.axisSpinBox_5.setValue(90)

        self.axisSpinBoxVertical.addWidget(self.axisSpinBox_5)

        self.axisSpinBox_6 = QSpinBox(self.horizontalLayoutWidget)
        self.axisSpinBox_6.setObjectName(u"axisSpinBox_6")
        self.axisSpinBox_6.setKeyboardTracking(False)
        self.axisSpinBox_6.setMaximum(130)
        self.axisSpinBox_6.setValue(90)

        self.axisSpinBoxVertical.addWidget(self.axisSpinBox_6)


        self.horizontalLayout.addLayout(self.axisSpinBoxVertical)

        self.axisSliderVertical = QVBoxLayout()
        self.axisSliderVertical.setObjectName(u"axisSliderVertical")
        self.axisSlider = QSlider(self.horizontalLayoutWidget)
        self.axisSlider.setObjectName(u"axisSlider")
        self.axisSlider.setMaximum(360)
        self.axisSlider.setPageStep(36)
        self.axisSlider.setValue(180)
        self.axisSlider.setOrientation(Qt.Horizontal)
        self.axisSlider.setInvertedAppearance(False)
        self.axisSlider.setInvertedControls(False)
        self.axisSlider.setTickPosition(QSlider.TicksBelow)

        self.axisSliderVertical.addWidget(self.axisSlider)

        self.axisSlider_2 = QSlider(self.horizontalLayoutWidget)
        self.axisSlider_2.setObjectName(u"axisSlider_2")
        self.axisSlider_2.setMaximum(180)
        self.axisSlider_2.setValue(130)
        self.axisSlider_2.setOrientation(Qt.Horizontal)
        self.axisSlider_2.setTickPosition(QSlider.TicksBelow)
        self.axisSlider_2.setTickInterval(10)

        self.axisSliderVertical.addWidget(self.axisSlider_2)

        self.axisSlider_3 = QSlider(self.horizontalLayoutWidget)
        self.axisSlider_3.setObjectName(u"axisSlider_3")
        self.axisSlider_3.setMaximum(180)
        self.axisSlider_3.setValue(180)
        self.axisSlider_3.setOrientation(Qt.Horizontal)
        self.axisSlider_3.setTickPosition(QSlider.TicksBelow)
        self.axisSlider_3.setTickInterval(10)

        self.axisSliderVertical.addWidget(self.axisSlider_3)

        self.axisSlider_4 = QSlider(self.horizontalLayoutWidget)
        self.axisSlider_4.setObjectName(u"axisSlider_4")
        self.axisSlider_4.setMaximum(180)
        self.axisSlider_4.setValue(60)
        self.axisSlider_4.setOrientation(Qt.Horizontal)
        self.axisSlider_4.setTickPosition(QSlider.TicksBelow)
        self.axisSlider_4.setTickInterval(10)

        self.axisSliderVertical.addWidget(self.axisSlider_4)

        self.axisSlider_5 = QSlider(self.horizontalLayoutWidget)
        self.axisSlider_5.setObjectName(u"axisSlider_5")
        self.axisSlider_5.setMaximum(180)
        self.axisSlider_5.setValue(90)
        self.axisSlider_5.setOrientation(Qt.Horizontal)
        self.axisSlider_5.setTickPosition(QSlider.TicksBelow)
        self.axisSlider_5.setTickInterval(10)

        self.axisSliderVertical.addWidget(self.axisSlider_5)

        self.axisSlider_6 = QSlider(self.horizontalLayoutWidget)
        self.axisSlider_6.setObjectName(u"axisSlider_6")
        self.axisSlider_6.setMaximum(130)
        self.axisSlider_6.setValue(90)
        self.axisSlider_6.setOrientation(Qt.Horizontal)
        self.axisSlider_6.setTickPosition(QSlider.TicksBelow)
        self.axisSlider_6.setTickInterval(10)

        self.axisSliderVertical.addWidget(self.axisSlider_6)


        self.horizontalLayout.addLayout(self.axisSliderVertical)

        self.tabWidget.addTab(self.sliderTab, "")
        self.buttonTab = QWidget()
        self.buttonTab.setObjectName(u"buttonTab")
        self.baseGroup = QGroupBox(self.buttonTab)
        self.baseGroup.setObjectName(u"baseGroup")
        self.baseGroup.setGeometry(QRect(30, 50, 161, 171))
        self.baseUp = QPushButton(self.baseGroup)
        self.baseUp.setObjectName(u"baseUp")
        self.baseUp.setGeometry(QRect(60, 40, 41, 41))
        self.baseDown = QPushButton(self.baseGroup)
        self.baseDown.setObjectName(u"baseDown")
        self.baseDown.setGeometry(QRect(60, 120, 41, 41))
        self.baseRight = QPushButton(self.baseGroup)
        self.baseRight.setObjectName(u"baseRight")
        self.baseRight.setGeometry(QRect(100, 80, 41, 41))
        self.baseRight.setAutoDefault(False)
        self.baseRight.setFlat(False)
        self.baseLeft = QPushButton(self.baseGroup)
        self.baseLeft.setObjectName(u"baseLeft")
        self.baseLeft.setGeometry(QRect(20, 80, 41, 41))
        self.wristGroup = QGroupBox(self.buttonTab)
        self.wristGroup.setObjectName(u"wristGroup")
        self.wristGroup.setGeometry(QRect(330, 50, 101, 171))
        self.wristUp = QPushButton(self.wristGroup)
        self.wristUp.setObjectName(u"wristUp")
        self.wristUp.setGeometry(QRect(30, 40, 41, 41))
        self.wristDown = QPushButton(self.wristGroup)
        self.wristDown.setObjectName(u"wristDown")
        self.wristDown.setGeometry(QRect(30, 120, 41, 41))
        self.elbowGroup = QGroupBox(self.buttonTab)
        self.elbowGroup.setObjectName(u"elbowGroup")
        self.elbowGroup.setGeometry(QRect(210, 50, 101, 171))
        self.elbowUp = QPushButton(self.elbowGroup)
        self.elbowUp.setObjectName(u"elbowUp")
        self.elbowUp.setGeometry(QRect(30, 40, 41, 41))
        self.elbowDown = QPushButton(self.elbowGroup)
        self.elbowDown.setObjectName(u"elbowDown")
        self.elbowDown.setGeometry(QRect(30, 120, 41, 41))
        self.stepGroup = QGroupBox(self.buttonTab)
        self.stepGroup.setObjectName(u"stepGroup")
        self.stepGroup.setGeometry(QRect(30, 250, 191, 91))
        self.stepUp = QPushButton(self.stepGroup)
        self.stepUp.setObjectName(u"stepUp")
        self.stepUp.setGeometry(QRect(130, 40, 51, 41))
        self.stepDown = QPushButton(self.stepGroup)
        self.stepDown.setObjectName(u"stepDown")
        self.stepDown.setGeometry(QRect(10, 40, 51, 41))
        self.stepSize = QSpinBox(self.stepGroup)
        self.stepSize.setObjectName(u"stepSize")
        self.stepSize.setGeometry(QRect(70, 40, 55, 41))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepSize.sizePolicy().hasHeightForWidth())
        self.stepSize.setSizePolicy(sizePolicy)
        self.stepSize.setMaximumSize(QSize(55, 41))
        self.stepSize.setFocusPolicy(Qt.NoFocus)
        self.stepSize.setFrame(False)
        self.stepSize.setAlignment(Qt.AlignCenter)
        self.stepSize.setReadOnly(True)
        self.stepSize.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.stepSize.setKeyboardTracking(False)
        self.stepSize.setMinimum(1)
        self.stepSize.setMaximum(20)
        self.stepSize.setValue(10)
        self.label = QLabel(self.buttonTab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(250, 240, 312, 256))
        self.label.setTextFormat(Qt.AutoText)
        self.label.setPixmap(QPixmap(u"images/robot_arm_layout.png"))
        self.label.setScaledContents(True)
        self.label.setTextInteractionFlags(Qt.NoTextInteraction)
        self.gripperGroup = QGroupBox(self.buttonTab)
        self.gripperGroup.setObjectName(u"gripperGroup")
        self.gripperGroup.setGeometry(QRect(450, 50, 171, 171))
        self.gripOpen = QPushButton(self.gripperGroup)
        self.gripOpen.setObjectName(u"gripOpen")
        self.gripOpen.setGeometry(QRect(100, 40, 51, 41))
        font = QFont()
        font.setPointSize(10)
        self.gripOpen.setFont(font)
        self.rotAntiClk = QPushButton(self.gripperGroup)
        self.rotAntiClk.setObjectName(u"rotAntiClk")
        self.rotAntiClk.setGeometry(QRect(20, 120, 41, 41))
        self.rotClk = QPushButton(self.gripperGroup)
        self.rotClk.setObjectName(u"rotClk")
        self.rotClk.setGeometry(QRect(20, 40, 41, 41))
        self.gripClose = QPushButton(self.gripperGroup)
        self.gripClose.setObjectName(u"gripClose")
        self.gripClose.setGeometry(QRect(100, 120, 51, 41))
        self.gripClose.setFont(font)
        self.tabWidget.addTab(self.buttonTab, "")
        self.controllerTab = QWidget()
        self.controllerTab.setObjectName(u"controllerTab")
        self.controllerControls = QLabel(self.controllerTab)
        self.controllerControls.setObjectName(u"controllerControls")
        self.controllerControls.setGeometry(QRect(140, 10, 521, 341))
        self.controllerControls.setPixmap(QPixmap(u"images/blank controller.png"))
        self.controllerControls.setScaledContents(True)
        self.reconnectControllerButton = QPushButton(self.controllerTab)
        self.reconnectControllerButton.setObjectName(u"reconnectControllerButton")
        self.reconnectControllerButton.setGeometry(QRect(270, 420, 251, 41))
        self.controllerStatusLabel = QLabel(self.controllerTab)
        self.controllerStatusLabel.setObjectName(u"controllerStatusLabel")
        self.controllerStatusLabel.setGeometry(QRect(270, 460, 91, 33))
        self.controllerStatus = QLabel(self.controllerTab)
        self.controllerStatus.setObjectName(u"controllerStatus")
        self.controllerStatus.setGeometry(QRect(360, 460, 181, 33))
        self.controllerStatus.setTextFormat(Qt.RichText)
        self.label_2 = QLabel(self.controllerTab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 360, 171, 151))
        self.label_2.setTextFormat(Qt.AutoText)
        self.label_2.setPixmap(QPixmap(u"images/robot_arm_layout.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setTextInteractionFlags(Qt.NoTextInteraction)
        self.label_4 = QLabel(self.controllerTab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(600, 360, 171, 151))
        self.label_4.setTextFormat(Qt.AutoText)
        self.label_4.setPixmap(QPixmap(u"images/robot_arm_layout.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setTextInteractionFlags(Qt.NoTextInteraction)
        self.tabWidget.addTab(self.controllerTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 801, 20))
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menuMenu.addAction(self.aboutAction)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.exitAction)

        self.retranslateUi(MainWindow)
        self.axisSlider.valueChanged.connect(self.axisSpinBox.setValue)
        self.axisSpinBox.valueChanged.connect(self.axisSlider.setValue)
        self.axisSpinBox_2.valueChanged.connect(self.axisSlider_2.setValue)
        self.axisSlider_2.valueChanged.connect(self.axisSpinBox_2.setValue)
        self.axisSpinBox_3.valueChanged.connect(self.axisSlider_3.setValue)
        self.axisSlider_3.valueChanged.connect(self.axisSpinBox_3.setValue)
        self.axisSpinBox_4.valueChanged.connect(self.axisSlider_4.setValue)
        self.axisSlider_4.valueChanged.connect(self.axisSpinBox_4.setValue)
        self.axisSpinBox_5.valueChanged.connect(self.axisSlider_5.setValue)
        self.axisSlider_5.valueChanged.connect(self.axisSpinBox_5.setValue)
        self.axisSpinBox_6.valueChanged.connect(self.axisSlider_6.setValue)
        self.axisSlider_6.valueChanged.connect(self.axisSpinBox_6.setValue)
        self.stepUp.clicked.connect(self.stepSize.stepUp)
        self.stepDown.clicked.connect(self.stepSize.stepDown)

        self.tabWidget.setCurrentIndex(0)
        self.baseLeft.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Robot Arm Control", None))
        self.aboutAction.setText(QCoreApplication.translate("MainWindow", u"&About", None))
        self.exitAction.setText(QCoreApplication.translate("MainWindow", u"&Exit", None))
        self.refreshButton.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.connectionLabel.setText(QCoreApplication.translate("MainWindow", u"Connection:", None))
#if QT_CONFIG(tooltip)
        self.connectButton.setToolTip(QCoreApplication.translate("MainWindow", u"Connect to Port", None))
#endif // QT_CONFIG(tooltip)
        self.connectButton.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.statusLabel.setText(QCoreApplication.translate("MainWindow", u"Status: N/A", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">How to use this application:</span></p><p><span style=\" font-size:16pt;\">First connect to the Robot Arm over USB, then power it on and then connect it above using the correct serial port.</span></p><p><span style=\" font-size:16pt;\">To control the Robot Arm, select the Sliders, Button Mode or Controller Mode tab.</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setupTab), QCoreApplication.translate("MainWindow", u"Setup", None))
        self.axisLabel.setText(QCoreApplication.translate("MainWindow", u"Base", None))
        self.axisLabel_2.setText(QCoreApplication.translate("MainWindow", u"Shoulder", None))
        self.axisLabel_3.setText(QCoreApplication.translate("MainWindow", u"Elbow", None))
        self.axisLabel_4.setText(QCoreApplication.translate("MainWindow", u"Lower Arm", None))
        self.axisLabel_5.setText(QCoreApplication.translate("MainWindow", u"Wrist", None))
        self.axisLabel_6.setText(QCoreApplication.translate("MainWindow", u"Gripper", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sliderTab), QCoreApplication.translate("MainWindow", u"Sliders", None))
        self.baseGroup.setTitle(QCoreApplication.translate("MainWindow", u"Base Control", None))
#if QT_CONFIG(tooltip)
        self.baseUp.setToolTip(QCoreApplication.translate("MainWindow", u"Move Arm Forward", None))
#endif // QT_CONFIG(tooltip)
        self.baseUp.setText(QCoreApplication.translate("MainWindow", u"\u2191", None))
#if QT_CONFIG(tooltip)
        self.baseDown.setToolTip(QCoreApplication.translate("MainWindow", u"Move Arm Back", None))
#endif // QT_CONFIG(tooltip)
        self.baseDown.setText(QCoreApplication.translate("MainWindow", u"\u2193", None))
#if QT_CONFIG(tooltip)
        self.baseRight.setToolTip(QCoreApplication.translate("MainWindow", u"Rotate Base Right", None))
#endif // QT_CONFIG(tooltip)
        self.baseRight.setText(QCoreApplication.translate("MainWindow", u"\u2192", None))
#if QT_CONFIG(tooltip)
        self.baseLeft.setToolTip(QCoreApplication.translate("MainWindow", u"Rotate Base Left", None))
#endif // QT_CONFIG(tooltip)
        self.baseLeft.setText(QCoreApplication.translate("MainWindow", u"\u2190", None))
        self.wristGroup.setTitle(QCoreApplication.translate("MainWindow", u"Wrist Control", None))
#if QT_CONFIG(tooltip)
        self.wristUp.setToolTip(QCoreApplication.translate("MainWindow", u"Move Wrist Up", None))
#endif // QT_CONFIG(tooltip)
        self.wristUp.setText(QCoreApplication.translate("MainWindow", u"\u2191", None))
#if QT_CONFIG(tooltip)
        self.wristDown.setToolTip(QCoreApplication.translate("MainWindow", u"Move Wrist Down", None))
#endif // QT_CONFIG(tooltip)
        self.wristDown.setText(QCoreApplication.translate("MainWindow", u"\u2193", None))
        self.elbowGroup.setTitle(QCoreApplication.translate("MainWindow", u"Elbow Control", None))
#if QT_CONFIG(tooltip)
        self.elbowUp.setToolTip(QCoreApplication.translate("MainWindow", u"Move Elbow Up", None))
#endif // QT_CONFIG(tooltip)
        self.elbowUp.setText(QCoreApplication.translate("MainWindow", u"\u2191", None))
#if QT_CONFIG(tooltip)
        self.elbowDown.setToolTip(QCoreApplication.translate("MainWindow", u"Move Elbow Down", None))
#endif // QT_CONFIG(tooltip)
        self.elbowDown.setText(QCoreApplication.translate("MainWindow", u"\u2193", None))
        self.stepGroup.setTitle(QCoreApplication.translate("MainWindow", u"Step Control", None))
#if QT_CONFIG(tooltip)
        self.stepUp.setToolTip(QCoreApplication.translate("MainWindow", u"Increase Step Rate", None))
#endif // QT_CONFIG(tooltip)
        self.stepUp.setText(QCoreApplication.translate("MainWindow", u"++", None))
#if QT_CONFIG(tooltip)
        self.stepDown.setToolTip(QCoreApplication.translate("MainWindow", u"Decrease Step Rate", None))
#endif // QT_CONFIG(tooltip)
        self.stepDown.setText(QCoreApplication.translate("MainWindow", u"--", None))
#if QT_CONFIG(tooltip)
        self.stepSize.setToolTip(QCoreApplication.translate("MainWindow", u"Step Size", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.label.setToolTip(QCoreApplication.translate("MainWindow", u"Robot Arm Sections", None))
#endif // QT_CONFIG(tooltip)
        self.label.setText("")
        self.gripperGroup.setTitle(QCoreApplication.translate("MainWindow", u"Gripper Control", None))
#if QT_CONFIG(tooltip)
        self.gripOpen.setToolTip(QCoreApplication.translate("MainWindow", u"Open Gripper", None))
#endif // QT_CONFIG(tooltip)
        self.gripOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(tooltip)
        self.rotAntiClk.setToolTip(QCoreApplication.translate("MainWindow", u"Rotate Gripper Anti-Clockwise", None))
#endif // QT_CONFIG(tooltip)
        self.rotAntiClk.setText(QCoreApplication.translate("MainWindow", u"\u21ba", None))
#if QT_CONFIG(tooltip)
        self.rotClk.setToolTip(QCoreApplication.translate("MainWindow", u"Rotate Gripper Clockwise", None))
#endif // QT_CONFIG(tooltip)
        self.rotClk.setText(QCoreApplication.translate("MainWindow", u"\u21bb", None))
#if QT_CONFIG(tooltip)
        self.gripClose.setToolTip(QCoreApplication.translate("MainWindow", u"Close Gripper", None))
#endif // QT_CONFIG(tooltip)
        self.gripClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buttonTab), QCoreApplication.translate("MainWindow", u"Button Mode", None))
        self.controllerControls.setText("")
        self.reconnectControllerButton.setText(QCoreApplication.translate("MainWindow", u"Get Controller Status", None))
        self.controllerStatusLabel.setText(QCoreApplication.translate("MainWindow", u"Status:", None))
        self.controllerStatus.setText(QCoreApplication.translate("MainWindow", u"N/A", None))
#if QT_CONFIG(tooltip)
        self.label_2.setToolTip(QCoreApplication.translate("MainWindow", u"Robot Arm Sections", None))
#endif // QT_CONFIG(tooltip)
        self.label_2.setText("")
#if QT_CONFIG(tooltip)
        self.label_4.setToolTip(QCoreApplication.translate("MainWindow", u"Robot Arm Sections", None))
#endif // QT_CONFIG(tooltip)
        self.label_4.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.controllerTab), QCoreApplication.translate("MainWindow", u"Controller Mode", None))
        self.menuMenu.setTitle(QCoreApplication.translate("MainWindow", u"&Menu", None))
    # retranslateUi

